version: '3.8'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    network_mode: bridge
    x-tinkr:
      cpu: 512
      memory: 512
      load_balancer:
        - tenancy: shared
          type: webserver
          healthcheck:
            path: /
            success_code: 200-299
            port: 32400
        - tenancy: shared
          type: webserver
          healthcheck:
            path: /
            success_code: 200-299
            port: 8324
        - tenancy: dedicated
          type: network
          port: 32469
        - tenancy: dedicated
          type: network
          port: 32410
        - tenancy: dedicated
          type: network
          port: 32412
        - tenancy: dedicated
          type: network
          port: 32413
        - tenancy: dedicated
          type: network
          port: 32414
        - tenancy: dedicated
          type: network
          port: 3005
    environment:
      - PLEX_CLAIM=claim-xxxxxx  # Replace with your actual claim token
      - ADVERTISE_IP=http://your-public-ip:32400/
      - TZ=Europe/London
    ports:
      - "32400:32400/tcp"  # Plex Web UI
      - "32469:32469/tcp"  # Plex DLNA
      - "32410:32410/udp"  # Plex GDM
      - "32412:32412/udp"  # Plex GDM
      - "32413:32413/udp"  # Plex GDM
      - "32414:32414/udp"  # Plex GDM
      - "8324:8324/tcp"    # Plex companion
      - "3005:3005/tcp"    # Plex HTPC
    volumes:
      - /path/to/plex/config:/config
      - /path/to/plex/transcode:/transcode
      - /path/to/plex/data:/data

  db:
    image: mariadb:10.6.4-focal
    restart: always
    x-tinkr:
      load_balancer:
        tenancy: dedicated
        type: network
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    x-tinkr:
      environment: 
        - WORDPRESS_DB_HOST=<hostname:db>
      load_balancer:
        tenancy: shared
        type: webserver
        healthcheck:
          timeout: 10
          healthy-threshold: 3
          unhealthy-threshold: 5
          port: 80
          path: /
          interval: 120
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /path/to/wordpress/config:/config
      - /path/to/wordpress/data:/data
