version: '3.8'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    x-tinkr:
      cpu: 512
      memory: 512
      environment:
        - PLEX_CLAIM=claim-xxxxxx  
        - ADVERTISE_IP=http://your-public-ip:32400/
        - TZ=Europe/London
      network:
        public: true  
      ports:
        plex-web:
          port: 32400
          protocol: http
          public: true
          healthcheck:
            path: /
            success_code: 200-299
            interval: 30
            timeout: 5
            retries: 3
        # plex-dlna:
        #   port: 32469
        #   protocol: http
        #   public: false 
        plex-gdm-1:
          port: 32410
          protocol: udp
          public: false  # Internal access only
        plex-gdm-2:
          port: 32412
          protocol: udp
          public: false  # Internal access only
        plex-gdm-3:
          port: 32413
          protocol: udp
          public: false  # Internal access only
        # plex-gdm-4:
        #   port: 32414
        #   protocol: udp
        #   public: false  # Internal access only
        # plex-companion:
        #   port: 8324
        #   protocol: tcp
        #   public: false  # Internal access only
        # plex-htpc:
        #   port: 3005
        #   protocol: tcp
        #   public: false  # Internal access only
    environment:
      - PLEX_CLAIM=claim-xxxxxx   
      - ADVERTISE_IP=http://your-public-ip:32400/
      - TZ=Europe/London
    volumes:
      - plex_data:/var/lib/ghost/content
