version: '3.8'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    network_mode: bridge
    x-tinkr:
      cpu: 512
      memory: 512
      load_balancer:
        - tenancy: shared
          type: webserver
          port: 32400
          protocol: tcp
          healthcheck:
            path: /
            success_code: 200-299
        - tenancy: dedicated
          type: network
          port: 32469
          protocol: tcp
        - tenancy: dedicated
          type: network
          port: 32410
          protocol: udp
        - tenancy: dedicated
          type: network
          port: 32412
          protocol: udp
        - tenancy: dedicated
          type: network
          port: 32413
          protocol: udp
    environment:
      - PLEX_CLAIM=claim-xxxxxx
      - ADVERTISE_IP=http://your-public-ip:32400/
      - TZ=Europe/London
    ports:
      - "32400:32400/tcp"
      - "32469:32469/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "8324:8324/tcp"
      - "3005:3005/tcp"
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - plex_data:/data

volumes:
  plex_config:
  plex_transcode:
  plex_data:
